Fix annoying attibute __file__ not found
AttributeError: 'App' object has no attribute '__file__' was always
happening when parsing oneplay-dvd.package because at the prepare()
method, the __file__ attribute was not set yet. This commit ensures
it's set before calling any method.