pkg-config: Fix strange issue if python2 is installed
Issue:
```
Running command ['/usr/bin/python3', 'setup.py', 'install', '--prefix', '/opt/fluendo-codecs-linux-x86/build-tools', '--root', '/']
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
ImportError: bad magic number in 'site': b'\x03\xf3\r\n'

Current thread 0x00007f271e52a700 (most recent call first):
<no Python frame>

Recipe 'meson' failed at the build step 'install'
```

The error is that file
PREFIX/build-tools/lib/python3.8/site-packages/site.pyc is a python
2.7 byte-compiled

The site.pyc file is generated by the pkg-config.recipe when site.py
is copied from setuptools(see commit e48dce5b), because it uses python
in `gen-iswide-table.py`. The script uses `#!/usr/bin/python` and if
python2 is installed the site.pyc is created.

Workaround: Use PYTHONDONTWRITEBYTECODE in this recipe to avoid write
`.pyc` files.