build-tools: Install meson as flat egg
In ubuntu xenial, meson is not recognized inside
flu-codec-sdk shell environment

A special case is added for macOS to avoid:

```
ImportError: bad magic number in 'site': b'\x03\xf3\r\n'
```

Issue: OCP-1293