m4.recipe: Bump to 1.4.19 to fix build error on Fedora 35
ccache gcc  -I.   -Wall -g -O2   -m64  -Wall -g -O2  -Wno-error=cast-align -MT closeout.o -MD -MP -MF $depbase.Tpo -c -o closeout.o closeout.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/789>